#!/bin/bash
echo "=== Задание 1-3: Создание вложенных директорий и файла ==="
echo ""
echo "1. Создаю директории level1/level2/level3..."
mkdir -p level1/level2/level3
echo "   ✓ Директории созданы"
echo ""
echo "2. Создаю файл secret.txt в level3..."
SECRET_FILE="level1/level2/level3/secret.txt"
echo "Секретные данные" > "$SECRET_FILE"
echo "   ✓ Файл secret.txt создан"
echo ""
echo "3. Устанавливаю права доступа 600..."
chmod 600 "$SECRET_FILE"
echo "   ✓ Права доступа установлены"
echo ""
echo "4. Проверяю права доступа..."
ls -la "level1/level2/level3/" | grep "secret.txt"
echo ""
echo "5. Полный путь к файлу:"
ABS_PATH="$(pwd)/level1/level2/level3/secret.txt"
echo "   $ABS_PATH"
echo ""
echo "=== Готово! ==="